### ISSUE TITLE
Почему четвертушка = 3 ?

### ISSUE THREAD

**Issue by evildoer** [KanatnikovMax/znanie-drevnix#46]
https://github.com/KanatnikovMax/znanie-drevnix/blob/7b2504e117da76e7833ccc695151b8dc4c8611b7/header/%D0%92%D0%B5_%D0%BA%D1%80%D0%B5%D1%81%D1%82_%D0%BA%D1%80%D0%B5%D1%81%D1%82.h#L96C73-L96C73
Это разве не 4 ? 😅

**Comment by evildoer** [comment]
Как и `осьмушка = 4` -- восьмая часть чего-либо...

**Comment by git-gud-casual** [comment]
Юрий предложил «счёт древних русов», как по его мнению считали наши предки. Состоит он из следующих форм: «ноль, целковый, полушка, четвертушка, осьмушка, пудовичок, медячок, серебрячок, золотничок, девятичок, десятичок». https://ru.wikinews.org/wiki/%D0%A3%D0%BC%D0%B5%D1%80_%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8C_%D1%81%D1%87%D1%91%D1%82%D0%B0_%D0%B4%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D1%85_%D1%80%D1%83%D1%81%D0%BE%D0%B2_%D0%B8_%D0%B3%D0%B5%D1%80%D0%BE%D0%B9_%D0%A8%D0%A3%D0%95_%D0%9F%D0%9F%D0%A8#:~:text=%D0%AE%D1%80%D0%B8%D0%B9%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B8%D0%BB%20%C2%AB%D1%81%D1%87%D1%91%D1%82%20%D0%B4%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D1%85%20%D1%80%D1%83%D1%81%D0%BE%D0%B2,%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BD%D0%B8%D1%87%D0%BE%D0%BA%2C%20%D0%B4%D0%B5%D0%B2%D1%8F%D1%82%D0%B8%D1%87%D0%BE%D0%BA%2C%20%D0%B4%D0%B5%D1%81%D1%8F%D1%82%D0%B8%D1%87%D0%BE%D0%BA%C2%BB.

**Comment by git-gud-casual** [comment]
Учи матчасть

**Comment by Dopaminos** [comment]
Поспорю.
Счёт был в "двоичной" системе счисления, поэтому перевод в десятичную неуместен
https://www.youtube.com/watch?v=jC2ARTI3fsQ
