### ISSUE TITLE
Неправильное имя хэдэр-файла в примерах

### ISSUE THREAD

**Issue by GrindelfP** [KanatnikovMax/znanie-drevnix#8]
Похоже, автор забыл изменить имя хэдер-файла в библиотеке с примером. В обоих файлах-примерах есть такая строчка:

`#include "СлавянскийC++.h"`

Но заголовочный файл библиотеки называется Ве_крест_крест.h, так что нужно иклюды переделать. Речь о стоках 1 в файлах [https://github.com/KanatnikovMax/znanie-drevnix/blob/main/examples/Сортировочка.cpp](Сортировочка.cpp) и [https://github.com/KanatnikovMax/znanie-drevnix/blob/main/examples/Слава_Руси.cpp](Слава_Руси.cpp).

**Comment by KanatnikovMax** [comment]
Да, действительно забыл, спасибо что обратили внимание
